//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fierce.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSeqNumber
    {
        public OrderSeqNumber()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int Id { get; set; }
        public int OrderId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public int Quantity { get; set; }
        public string Type { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
