//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fierce.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PunchOutRequest
    {
        public PunchOutRequest()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string RequestExtrinsicUser { get; set; }
        public string RequestSupplierPartID { get; set; }
        public string RequestExtrinsicRevision { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string PunchOutXml { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
