//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fierce.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class XmlResponse
    {
        public int ID { get; set; }
        public string FromIdentity { get; set; }
        public string ToIdentity { get; set; }
        public string SenderIdentity { get; set; }
        public string SharedSecret { get; set; }
        public string UserAgent { get; set; }
        public string BuyerCookie { get; set; }
        public string Extrinsic_user { get; set; }
        public string BrowserFormPost_Url { get; set; }
        public string Email { get; set; }
        public string SupplierSetup_Url { get; set; }
        public string Extrinsic_SessionId { get; set; }
        public string SupplierPartID { get; set; }
        public string SupplierPartAuxiliaryID { get; set; }
        public string Extrinsic_Revision { get; set; }
    }
}
