//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fierce.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderSeqNumbers = new HashSet<OrderSeqNumber>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string UserName { get; set; }
        public int PunchID { get; set; }
        public Nullable<int> DROrderId { get; set; }
        public string TotalMoney { get; set; }
        public string ShipAddress { get; set; }
        public string ShipName { get; set; }
        public string ShipDeliverTo { get; set; }
        public string ShipStreet { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountry { get; set; }
        public string BillAddress { get; set; }
        public string BillName { get; set; }
        public string BillStreet { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillPostalCode { get; set; }
        public string BillCountry { get; set; }
        public string UnitPriceMoney { get; set; }
        public string ChargeMoney { get; set; }
        public string UnitOfMeasure { get; set; }
        public string LeadTime { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string ExtrinsicDeliveryType { get; set; }
        public string ExtrinsicPlacedByUser { get; set; }
        public string SupplierPartAuxiliaryID { get; set; }
        public string ProjectName { get; set; }
    
        public virtual ICollection<OrderSeqNumber> OrderSeqNumbers { get; set; }
        public virtual PunchOutRequest PunchOutRequest { get; set; }
    }
}
